# Generated by Django 3.2.9 on 2021-11-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='breed',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finch',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='finch',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
